apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
type: Opaque
data:
  INFLUX_TOKEN: YkplQkI2dHVPWk5ZZlBSUGpVYks0RTBNQ09ScEUyRmNtMWtxZTIxR2NRZGtBMEJkZW9BZDVqeS1KaldwS3VDMTFsMHN5WHM1eDlHZjVHbHpPMkRQSWc9PQ==
  DOCKER_INFLUXDB_INIT_PASSWORD: bUc2M21ONTZqVzkzcHNmQg==