---
apiVersion: v1
kind: Service
metadata:
  name: service-fw-api-stats-db
spec:
  selector:
    app: fw-api-stats-db
  ports:
    - name: fw-api-stats-db
      protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP